version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
