name: JSR Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2.0.5
        with:
          deno-version: v2.x
          cache: true
      - run: deno publish
